name: dbt_data_engineering_toolkit
version: 6.0.0
config-version: 2

require-dbt-version: [">=1.10.6", "<3.0.0"]

macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages", "logs"]

vars:
  dbt_data_engineering_toolkit:
    audit_source_system: null
