-- Generated by det 6.0.0. Edit the workbook, not this file.
{{ config(materialized='table') }}

with source__crm_customers as (
    select * from {{ source('raw', 'raw_customers') }}
),

mapped as (
    select
        crm_customers.customer_id,
        crm_customers.customer_name,
        crm_customers.email,
        crm_customers.revenue,
        crm_customers.event_code as event_date_display,
        crm_customers.status_code as status_label
    from source__crm_customers as crm_customers
),

transformed_01 as (
    select
        {{ de_toolkit.clean_string(
            'customer_id',
            trim=true,
            collapse_whitespace=true,
            case='preserve',
            blank_as_null=true
        ) }} as customer_id,
        {{ de_toolkit.clean_string(
            'customer_name',
            trim=true,
            collapse_whitespace=true,
            case='upper',
            blank_as_null=true
        ) }} as customer_name,
        {{ de_toolkit.clean_email('email') }} as email,
        {{ de_toolkit.clean_numeric('revenue', precision=18, scale=2) }} as revenue,
        {{ de_toolkit.mapping(
            expression='event_date_display',
            mapping={
                'launch': '2026-09-04',
                'renewal': '2027-01-15'
            },
            default='2026-01-01',
            preserve_unmapped=false,
            case_sensitive=true,
            data_type='date',
            format={
                'pattern': '%d/%m/%Y'
            }
        ) }} as event_date_display,
        {{ de_toolkit.mapping(
            expression='status_label',
            mapping={
                'A': 'active',
                'I': 'inactive'
            },
            default='unknown',
            preserve_unmapped=false,
            case_sensitive=false,
            data_type='string',
            format={
                'case': 'upper'
            }
        ) }} as status_label
    from mapped
),

validated as (
    select
        *,
        {{ de_toolkit.is_email('email', allow_null=false) }} as _email_invalid_valid,
        {{ de_toolkit.is_positive('revenue', allow_null=true) }} as _revenue_not_positive_valid,
        customer_id is not null as _customer_id_operational_warning_valid
    from transformed_01
)

select
    customer_id,
    customer_name,
    email,
    revenue,
    event_date_display,
    status_label,
    {{ de_toolkit.assertions(column='_det_rejections') }},
    {{ de_toolkit.assertions(column='_det_warnings') }},
    {{ de_toolkit.audit_columns('crm') }}
from validated
