-- Generated by det 5.0.1. Edit the workbook, not this file.
{{ config(materialized='table') }}

with source__stg_customers as (
    select * from {{ ref('stg_customers') }}
),

source__raw_accounts as (
    select * from {{ source('raw', 'raw_accounts') }}
),

mapped as (
    select
        stg_customers.customer_id,
        stg_customers.account_id,
        stg_customers.customer_name,
        stg_customers.email,
        stg_customers.status_label,
        raw_accounts.account_tier,
        raw_accounts.lifetime_value
    from source__stg_customers as stg_customers
    left join source__raw_accounts as raw_accounts
        on stg_customers.account_id = raw_accounts.account_id
),

transformed_01 as (
    select
        customer_id,
        account_id,
        customer_name,
        email,
        status_label,
        {{ de_toolkit.clean_string('account_tier') }} as account_tier,
        {{ de_toolkit.clean_numeric('lifetime_value', precision=18, scale=2) }} as lifetime_value
    from mapped
),

validated as (
    select
        *,
        {{ de_toolkit.is_positive('lifetime_value', allow_null=false) }} as _value_not_positive_valid
    from transformed_01
)

select
    customer_id,
    account_id,
    customer_name,
    email,
    status_label,
    account_tier,
    lifetime_value,
    {{ de_toolkit.assertions(column='_det_rejections') }},
    {{ de_toolkit.audit_columns('raw_customers') }}
from validated
