"""Generated-project operator instructions."""

from __future__ import annotations

from ...adapters import AdapterRegistry
from ...models import DataProductSpecification
from ...version import COMPILER_VERSION


class GeneratedReadmeEmitter:
    def emit(self, spec: DataProductSpecification) -> str:
        git_env = spec.build.toolkit_git_env
        revision = spec.build.toolkit_revision
        provider = AdapterRegistry.default().get(spec.build.adapter)
        adapter_dependency = provider.dbt_dependency if provider else spec.build.adapter
        compiler_requirement = (
            f"dbt-data-engineering-toolkit-compiler[{provider.name}]=={COMPILER_VERSION}"
            if provider
            else f"dbt-data-engineering-toolkit-compiler=={COMPILER_VERSION}"
        )
        return f"""# {spec.metadata.name}

Generated from the controlled V{COMPILER_VERSION} ODCS-superset workbook. The SQL is intentionally
ordinary and reviewable: source/ref CTEs, inline `de_toolkit` calls, validation
flags, and explicit quarantine models.

## First deployment

0. Install the compiler and the selected dbt adapter. The default compiler install
already includes Data Contract CLI, dbt Core, DuckDB, and SQLFluff. This project
selects `{spec.build.adapter}` (`{adapter_dependency}`).

```bash
python -m pip install "{compiler_requirement}"
```

1. The generated two-package dependency graph uses the public toolkit repository by
default. Both entries are pinned to `{revision}`; the second entry installs the short
`de_toolkit` namespace from its subdirectory. Set this optional override for a fork or mirror:

```bash
export {git_env}=https://github.com/systemizing-solutions/dbt_data_engineering_toolkit.git
```

2. Install and lock dbt dependencies:

```bash
dbt deps
```

`dbt deps` installs packages into `dbt_packages/` and creates or updates
`package-lock.yml`. Commit the lock file for repeatable CI builds.

3. Contract synchronization is already part of `det generate`. Its normalized,
Windows-safe output and ownership hashes are recorded in `.det-manifest.json`.
Do not run Data Contract synchronization separately because that bypasses the
compiler's atomic publication, path normalization, and drift tracking.

4. Parse dbt and lint the rendered project:

```bash
dbt parse --profiles-dir .
sqlfluff lint models tests --config .sqlfluff
```

`profiles.yml` is generated by the `{spec.build.adapter}` adapter provider. Secret
values are environment-variable references; the workbook never stores credentials.
Set the referenced variables in your shell or deployment secret manager before dbt runs.

5. Load fixtures and build models and tests:

```bash
dbt seed --profiles-dir . --exclude package:dbt_project_evaluator
dbt build --profiles-dir . --exclude package:dbt_project_evaluator
```

6. Run project-quality evaluation as its own gate:

```bash
dbt seed --profiles-dir . --select package:dbt_project_evaluator
dbt run --profiles-dir . --select package:dbt_project_evaluator
```

The dbt manifest is generated by `dbt parse` or `dbt build` at
`target/manifest.json`. It is build output, not source control.

## Updating from the workbook

```bash
det status WORKBOOK --project-dir .
det workbook refresh WORKBOOK
det generate WORKBOOK --project-dir . --dry-run --prune
det generate WORKBOOK --project-dir . --prune
det check WORKBOOK --project-dir .
det prove WORKBOOK --project-dir .
```

When upstream ODCS, DDL, or dbt metadata changes, merge structure first; DET
mapping, parameter, rule, and lookup decisions remain available for review:

```bash
det workbook sync WORKBOOK --from-contract upstream.odcs.yaml
det workbook refresh WORKBOOK
```

## If generated code was edited

Do not reverse-sync arbitrary SQL into Excel. `det status` reports hand edits as
drift. Put business logic in the workbook, put custom SQL in a separate downstream
model, or change the appropriate emitter service and regenerate. `--force` is an
explicit reviewed recovery option, not the normal update path.

For one isolated acceptance run:

```bash
det prove WORKBOOK --project-dir .
```
"""
