-- Generated by det 5.0.0. Edit the workbook, not this file.
{{ config(materialized='view') }}

with source__raw_customers as (
    select * from {{ source('raw', 'raw_customers') }}
),

mapped as (
    select
        raw_customers.customer_id,
        raw_customers.account_id,
        raw_customers.customer_name,
        raw_customers.email,
        raw_customers.status_code as status_label
    from source__raw_customers as raw_customers
),

transformed_01 as (
    select
        {{ de_toolkit.clean_code('customer_id') }} as customer_id,
        {{ de_toolkit.clean_code('account_id') }} as account_id,
        {{ de_toolkit.clean_string('customer_name') }} as customer_name,
        {{ de_toolkit.clean_email('email') }} as email,
        {{ de_toolkit.mapping(
            expression='status_label',
            mapping={
                'A': 'active',
                'I': 'inactive'
            },
            default='unknown',
            data_type='string'
        ) }} as status_label
    from mapped
),

transformed_02 as (
    select
        customer_id,
        account_id,
        email,
        status_label,
        {{ de_toolkit.string_title('customer_name') }} as customer_name
    from transformed_01
),

validated as (
    select
        *,
        {{ de_toolkit.is_email('email', allow_null=true) }} as _email_warning_valid
    from transformed_02
)

select
    customer_id,
    account_id,
    customer_name,
    email,
    status_label,
    {{ de_toolkit.assertions(column='_det_warnings') }},
    {{ de_toolkit.audit_columns('raw_customers') }}
from validated
